annotations:
  artifacthub.io/repository: kubewarden-rego-policies-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Kustomization Prune
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/kustomization-prune
  kubewarden/resources: Kustomization
  kubewarden/rules: |
    - apiGroups:
      - kustomize.toolkit.fluxcd.io
      apiVersions:
      - v1
      resources:
      - kustomizations
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.0
appVersion: 1.0.0
description: The 'spec.prune' field in the Kustomization object must be set according
  to the input parameter 'prune'.
home: https://github.com/kubewarden/rego-policies-library
keywords:
- flux
name: kustomization-prune
sources:
- ghcr.io/kubewarden/policies/kustomization-prune:v1.0.0
version: 1.0.0
