annotations:
  artifacthub.io/repository: kubewarden-rego-policies-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Resource Quota Setting Is Missing
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/resource-quota-setting-is-missing
  kubewarden/resources: ResourceQuota
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - resourcequotas
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.0
appVersion: 1.0.0
description: |
  When creating resource quotas per namespace, ensure CPU and Memory requests and limits are set.
home: https://github.com/kubewarden/rego-policies-library
keywords:
- soc2-type1
name: resource-quota-setting-is-missing
sources:
- ghcr.io/kubewarden/policies/resource-quota-setting-is-missing:v1.0.0
version: 1.0.0
