annotations:
  artifacthub.io/repository: allow-privilege-escalation-psp
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Allow Privilege Escalation PSP
  kubewarden/mutation: "true"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/allow-privilege-escalation-psp
  kubewarden/resources: Deployment,Replicaset,Statefulset,Daemonset,Replicationcontroller,Job,Cronjob,Pod
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - pods
      operations:
      - CREATE
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - replicationcontrollers
      operations:
      - CREATE
      - UPDATE
    - apiGroups:
      - apps
      apiVersions:
      - v1
      resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
      operations:
      - CREATE
      - UPDATE
    - apiGroups:
      - batch
      apiVersions:
      - v1
      resources:
      - jobs
      - cronjobs
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v0.2.7
appVersion: 0.2.7
description: Replacement for the Kubernetes Pod Security Policy that controls the
  allowance of privilege escalation in containers and init containers of a pod
home: https://github.com/kubewarden/allow-privilege-escalation-psp-policy
keywords:
- PSP
- privilege escalation
name: allow-privilege-escalation-psp
sources:
- ghcr.io/kubewarden/policies/allow-privilege-escalation-psp:v0.2.7
version: 0.2.7
