annotations:
  artifacthub.io/repository: environment-variable-policy
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Environment Variable Policy
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/environment-variable-policy
  kubewarden/resources: Deployment,Replicaset,Statefulset,Daemonset,Replicationcontroller,Job,Cronjob,Pod
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - pods
      operations:
      - CREATE
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - replicationcontrollers
      operations:
      - CREATE
      - UPDATE
    - apiGroups:
      - apps
      apiVersions:
      - v1
      resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
      operations:
      - CREATE
      - UPDATE
    - apiGroups:
      - batch
      apiVersions:
      - v1
      resources:
      - jobs
      - cronjobs
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v0.1.7
appVersion: 0.1.7
description: A Kubewarden Policy that controls the usage of environment variables
home: https://github.com/kubewarden/environment-variable-policy
keywords:
- deployment
- replicaset
- statefulset
- daemonset
- replicationcontroller
- job
- cronjob
- pod
- container
- environment-variables
name: environment-variable-policy
sources:
- ghcr.io/kubewarden/policies/environment-variable-policy:v0.1.7
version: 0.1.7
