annotations:
  artifacthub.io/repository: kubewarden-rego-policies-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Helm Release Values From
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/helm-release-values-from-configmaps
  kubewarden/resources: HelmRelease
  kubewarden/rules: |
    - apiGroups:
      - helm.toolkit.fluxcd.io
      apiVersions:
      - v2
      resources:
      - helmreleases
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.1
appVersion: 1.0.1
description: HelmRelease valuesFrom must use correctly configured ConfigMaps.
home: https://github.com/kubewarden/rego-policies-library
keywords:
- flux
name: helm-release-values-from-configmaps
sources:
- ghcr.io/kubewarden/policies/helm-release-values-from-configmaps:v1.0.1
version: 1.0.1
