annotations:
  artifacthub.io/repository: safe-labels
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Safe Labels
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/safe-labels
  kubewarden/resources: '*'
  kubewarden/rules: |
    - apiGroups:
      - '*'
      apiVersions:
      - '*'
      resources:
      - '*'
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v0.1.14
appVersion: 0.1.14
description: A policy that validates Kubernetes' resource labels
home: https://github.com/kubewarden/safe-labels-policy
keywords:
- labels
name: safe-labels
sources:
- ghcr.io/kubewarden/policies/safe-labels:v0.1.14
version: 0.1.14
