annotations:
  artifacthub.io/repository: unique-service-selector
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/contextAwareResources: |
    - apiVersion: v1
      kind: Service
  kubewarden/displayName: Unique service selector
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/unique-service-selector-policy
  kubewarden/resources: Service
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - services
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.0
appVersion: 1.0.0
description: Policy validates that there are no services with the same set of selectors
home: https://github.com/kubewarden/unique-service-selector-policy
keywords:
- service
- selector
name: unique-service-selector-policy
sources:
- ghcr.io/kubewarden/policies/unique-service-selector-policy:v1.0.0
version: 1.0.0
