annotations:
  artifacthub.io/repository: ingress-policy
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Ingress Policy
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/ingress
  kubewarden/resources: Ingress
  kubewarden/rules: |
    - apiGroups:
      - networking.k8s.io
      apiVersions:
      - v1
      resources:
      - ingresses
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.2-rc1
appVersion: 1.0.2-rc1
description: Enforce requirements on Ingress resources
home: https://github.com/kubewarden/ingress-policy
keywords:
- ingress
name: ingress-policy
sources:
- ghcr.io/kubewarden/policies/ingress:v1.0.2-rc1
version: 1.0.2-rc1
