annotations:
  artifacthub.io/repository: container-resources
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Container Resources
  kubewarden/mutation: "true"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/container-resources
  kubewarden/resources: Pod, Replicationcontroller, Deployments, Replicaset, Statefulset,
    Daemonset, Job, Cronjob
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - pods
      operations:
      - CREATE
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - replicationcontrollers
      operations:
      - CREATE
      - UPDATE
    - apiGroups:
      - apps
      apiVersions:
      - v1
      resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
      operations:
      - CREATE
      - UPDATE
    - apiGroups:
      - batch
      apiVersions:
      - v1
      resources:
      - jobs
      - cronjobs
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v0.3.0
appVersion: 0.3.0
description: Policy is designed to enforce constraints on the resource requirements
  of Kubernetes containers
home: https://github.com/kubewarden/container-resources-policy
keywords:
- container
- resources
name: container-resources
sources:
- ghcr.io/kubewarden/policies/container-resources:v0.3.0
version: 0.3.0
