name: pkg2chart CI

on:
  push:
    branches: [main]
    paths:
      - "pkg2chart/**"
  pull_request:
    branches: [main]
    paths:
      - "pkg2chart/**"

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pkg2chart

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: ./pkg2chart/go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          working-directory: ./pkg2chart

      - name: Run tests
        run: go test -v ./...
